# unity_executable_path (str, optional): the path to the Unity executable to use
# to build the project. If not given, an attempt will be made to auto detect
# the Unity installation.
#
# unity_executable_path: "C:/Unity/Editor/Unity.exe"

# unity_preferred_version (str, optional): the preferred version of Unity to get
# when using Unity installation auto detection. If not given, it will use the
# first one it finds.
#
# unity_preferred_version: "2017.4.30f1"

# build_defs (array): the list of builds we should be making. Cannot be empty.
# Each build should have 'target (str)', which is one of https://docs.unity3d.com/ScriptReference/BuildTarget.html
# As well as 'executable_name (str)', which is the name of the executable to build.
#
build_defs:
  - target: StandaloneWindows
    executable_name: LSDR.exe
